### PR TITLE
Fix top banner and navigation styles/fixes

### LINKED ISSUE #172: Fix top banner issues
- Fix issues with scrolling overlapping header when scrolling

### PR DESCRIPTION
**Pull request by samuelopra**
Fix #172

Test URLs:
- Before: https://main--hubblehomes-com--aemsites.hlx.live/
- After: https://issue-172--hubblehomes-com--aemsites.hlx.live/

### CODE REVIEW

**Comment by bhellema** [comment]
Please take a look at the issue where the click area is now being overlapped by an element preventing the click from hitting the menu button.   There is also rendering issues when the menu is open.

https://github.com/user-attachments/assets/c4f28c34-e7ae-40b9-a91c-a93526d8b403

File: blocks/top-banner/top-banner.js [hunk 1]
```diff
@@ -39,12 +39,26 @@ export default function decorate(block) {
...
+      if (header) {
+        header.style.top = '0';
+      }
+
+      // Remove the inline max-height after the transition
       setTimeout(() => {
-        block.remove();
-      }, 300); // 300ms matches the transition duration in CSS
+        block.style.maxHeight = '';
+      }, 500); // 500ms matches the transition duration in CSS
```
Comment (bhellema) [inline blocks/top-banner/top-banner.js:60]: I thought maybe the code was going to look something like:
```
addEventListner('click', () => {
   documnet.querySelector('. top-banner').remove();
   sessionStorage.setItem('topBannerDismissed', 'true');
})
```

I'm surprised to see that we're playing with the body style's at all.  Just nuke the banner and allow the dom to reposition itself?

**Comment by dave-fink** [comment]
Mobile view (emulationg iphone 12 Pro) when you click burger then menu overlays the logo and burger button. 
image

**Comment by dave-fink** [comment]
Was it decided to not show the right column (fragment)?   If so we should remove the reference. 
Even if we aren't using it, I think we should still leave it as an option for the customer to use.  We can just put an example in the sidekick library. 

image

File: scripts/scripts.js [hunk 2]
```diff
@@ -137,13 +137,66 @@ export async function loadTemplate(doc, templateName) {
...
 async function loadTopBanner(doc) {
   const topBannerFragment = await loadFragment('/fragments/top-banner');
   if (topBannerFragment) {
     const topBanner = topBannerFragment.querySelector('.top-banner');
     if (topBanner) {
       const header = doc.querySelector('header');
       header?.prepend(topBanner);
+
+      // Dispatch a custom event when the banner is added
+      window.dispatchEvent(new CustomEvent('topbannerloaded'));
```
Comment (bhellema) [inline scripts/scripts.js:199]: I feel like non of this code is required if we just allow the dom to reposition itself.

Comment (samuelopra) [reply scripts/scripts.js:199]: I had to do this because of the way the site is already implemented. This is what happens when I allow it to reposition itself. This will require a lot of refactoring work to accomplish and we can do that in a different task.

Screenshot 2024-07-16 at 11 08 56 AM

**Comment by samuelopra** [comment]
> Was it decided to not show the right column (fragment)? If so we should remove the reference.
> Even if we aren't using it, I think we should still leave it as an option for the customer to use. We can just put an example in the sidekick library.

Weird, I thought I removed this reference

File: blocks/top-banner/top-banner.js (hunk 1 above)
Comment (samuelopra) [reply blocks/top-banner/top-banner.js:60]: see my comment below

**Comment by bhellema** [comment]
I had created a branch for my own observation for removing the spacing https://github.com/aemsites/hubblehomes-com/commit/08f96721fbc954e0ae73507d305143f191efcf79 it's here if you need it.

**Comment by samuelopra** [comment]
> Mobile view (emulationg iphone 12 Pro) when you click burger then menu overlays the logo and burger button. image

fixed

**Comment by samuelopra** [comment]
> Please see the video I added in my previous comment.

@bhellema please check that this is fixed

**Comment by dave-fink** [comment]
@samuelopra Looks good - but there's a conflict that needs to be resolved
